version: "2"

formatters:
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/a-novel-kit)
        - prefix(github.com/a-novel-kit/jwt)

linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustruct
    - varnamelen
    - revive
    - ireturn
    - gochecknoinits
    - gochecknoglobals
    - iface
    - funlen
    - funcorder
    - cyclop
    - err113
    - wrapcheck
    - mnd
    - forcetypeassert

  settings:
    gosec:
      excludes:
        - G115
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: goCamel

  exclusions:
    paths:
      - mocks
    rules:
      - path: (.+)_test.go
        linters:
          - maintidx
          - paralleltest
