name: main

on: [ push ]

jobs:
  test:
    uses: a-novel-kit/workflows/.github/workflows/test-go.yaml@master
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    uses: a-novel-kit/workflows/.github/workflows/deploy-pages.yaml@master
    if: github.ref == 'refs/heads/master' && success()
    permissions:
      contents: read
      pages: write
      id-token: write
