name: main

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/test-go@master

  lint-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/lint-go@master

  lint-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/lint-node@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          app_id: ${{ vars.DEPENDENCY_BOT_ID }}

  report-codecov:
    runs-on: ubuntu-latest
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/codecov@master
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  report-grc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/go-report-card@master
        if: github.ref == 'refs/heads/master' && success()

  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [test, lint-go, lint-node]
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: a-novel-kit/workflows/github-pages-actions/publish-vuepress@master
        with:
          working_directory: ./docs
          build_path: ./docs/.vitepress/dist/
